replicaCount: 2
image:
  repository: {{PLACEHOLDER_ACR}}/sample
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: sample
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: {{PLACEHOLDER_DNS}}
  annotations: {}
  path: /
  tls:
    enabled: false
resources: {}
env: []
podDisruptionBudget:
  enabled: true
  minAvailable: 1
